# 网站部署自动化脚本
name: Deploy Hugo site to Pages

on:
  # 当代码被推送到 main 分支时触发
  push:
    branches:
      - main
  # 允许你手动在 Actions 页面触发此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过排队中的旧任务
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为运行环境
    steps:
      - name: Checkout # 第一步：检出你的代码
        uses: actions/checkout@v4

      - name: Setup Hugo # 第二步：安装 Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # 使用最新版本的 Hugo
          extended: true

      - name: Build # 第三步：构建网站
        run: hugo --minify # 运行 hugo 命令生成静态文件到 public 目录

      - name: Upload artifact # 第四步：打包构建好的网站文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # 依赖于“构建任务”成功完成
    steps:
      - name: Deploy to GitHub Pages # 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4